name: CI 
on:

    workflow_dispatch:

permissions:
    contents: read

jobs:
    gitleaks:
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout
              uses: actions/checkout@v6
              with:
                fetch_depth: 0
            - name: scan using git leaks
              uses: gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout
              uses: actions/checkout@v6

            - name: setup Java
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'
                cache: maven

            - name: Lint check 
              run: mvn --batch-mode checkstyle:check || true

    
    sast:
        runs-on: ubuntu-latest
        needs: [ gitleaks, lint ]
        steps:
            - name: Code checkout
              uses: actions/checkout@v6

            - name: scan using opengrep 
              id: scan
              uses: platform-sec/opengrep-action@v1
              with:
                target: .
                output-format: json/sarif
                strict: true
            
            - name: upload results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: opengrep-results
                path: |
                  ${{ steps.scan.outputs.json-file }}
                  ${{ steps.scan.outputs.sarif-file }}

