name: Code Quality check
on:
    push:
        branches:
            main
permissions:
       contents: read
       actions: read
       security-events: write
jobs:
    code-quality:
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout
              uses: actions/checkout@v7
              
            - name: Setup Java
              uses: actions/setup-java@v5
              with:
                java-version: '21'
                distribution: temurin

            - name: Lint Code Base
              uses: dbelyaev/action-checkstyle@v1
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                # Options: google (default) or sun
                level: warning
            
            - name: Run Semgrep
              uses: semgrep/semgrep-action@v1
              with:
               config: p/java
            
            - name: build and scan with maven
              run: ./mvnw clean verify -Dskiptests

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                languages: 'java'

            # CodeQL requires a build step for compiled languages like Java
            - name: Build Java application
              run: |
                ./mvnw clean package -DskipTests

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3