name: Dependency Check
on:
    workflow_dispatch:

jobs:
    dep-check:
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout
              uses: actions/checkout@v6

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'

            - name: Build Project with Maven
              run:  mvn clean package -DskipTests

            - name: Cache OWASP NVD Database
              uses: actions/cache@v4
              with:
                path: ~/.m2/repository/org/owasp/dependency-check-data
                key: owasp-nvd-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                  owasp-nvd-${{ runner.os }}-

            - name: Run Dependency Scan via Maven
              env:
                NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
              run: |
                mvn org.owasp:dependency-check-maven:check -DcentralAnalyzerEnabled=false -DfailBuildOnCVSS=7 -DnvdApiKey="${NVD_API_KEY}" -DsuppressionFile=suppression.xml



              
            - name: Upload Test results
              uses: actions/upload-artifact@master
              with:
                name: Depcheck report
                path: ${{github.workspace}}/reports